import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { QueryClientProvider, QueryClient } from "@tanstack/react-query";
import "mapbox-gl/dist/mapbox-gl.css";

const gotham = localFont({
	src: "./fonts/montserrat/Montserrat-Medium.ttf",
	variable: "--font-heading-sans",
	weight: "500",
});

const montserrat = localFont({
	src: "./fonts/montserrat/Montserrat-Regular.ttf",
	variable: "--font-text-sans",
	weight: "400",
});

const bascimeAntique = localFont({
	src: "./fonts/bascime-antique/BacasimeAntique-Regular.ttf",
	variable: "--font-text-serif",
	weight: "400",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const client = new QueryClient();

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<QueryClientProvider client={client}>
				<body
					className={`${montserrat.variable} ${bascimeAntique.variable} ${gotham.variable} bg-white-background h-[120vh]`}>
					{children}
				</body>
			</QueryClientProvider>
		</html>
	);
}
